/**
 * Every widget's ROUTES-FROM-COLUMN block matches the column.
 *
 * The block is generated by scripts/generate_widget_routing_docs.py from
 * content/concept-archetypes.csv. This test re-derives it and compares, so a
 * column change that nobody re-stamped fails HERE, loudly — instead of a
 * widget header quietly describing routes that no longer exist, which is the
 * field_lines wired-and-unused failure in documentation form.
 */
import { execFileSync } from 'node:child_process';
import { resolve } from 'node:path';

const root = resolve(__dirname, '../../..');

test('routing doc blocks match content/concept-archetypes.csv', () => {
  // The generator IS the specification of the block; running it in --check
  // mode is the comparison, so there is exactly one implementation and the
  // test cannot drift from the script the way a re-implementation would.
  execFileSync('python3', [resolve(root, 'scripts/generate_widget_routing_docs.py'), '--check'], {
    stdio: 'pipe',
  });
});
