#!/usr/bin/env python3
"""Stamp each widget's index.tsx with what the COLUMN says routes to it.

    python3 scripts/generate_widget_routing_docs.py           # write
    python3 scripts/generate_widget_routing_docs.py --check   # drift-check, exit 1

WHY GENERATED AND NOT WRITTEN. A widget's header used to say what its author
believed it was for — the original design notes. The archetype column says
what actually routes to it, read from the book's own chunks, and the two
drift: field_lines shipped, was verified, was wired, and routed ZERO concepts
for days because nobody re-read the column when v2 landed. A hand-written
"used by" list is that failure waiting to repeat, so the list is stamped from
`content/concept-archetypes.csv` between markers, and a jest test regenerates
it in memory and fails on any difference. Regenerate rather than edit:

WHAT COUNTS. Only `v2_confidence == "high"` rows — that is the only band the
server routes on (archetype path). A widget showing zero is a FINDING, not a
formatting gap, and the block says so explicitly rather than omitting the
section.
"""
from __future__ import annotations

import argparse
import csv
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_PATH = os.path.join(ROOT, "content", "concept-archetypes.csv")

#: widget id -> directory under lib/widgets/
WIDGET_DIRS = {
    "projectile_motion": "projectile-motion",
    "molecule_3d": "molecule-3d",
    "field_lines": "field-lines",
    "free_body_forces": "free-body-forces",
    "xy_plot": "xy-plot",
    "data_table_trend": "data-table-trend",
    "process_flow": "process-flow",
    "reaction_scheme": "reaction-scheme",
    "molecule_struct": "molecule-struct",
    "circuit_network": "circuit-network",
    "lines_planes_3d": "lines-planes-3d",
}

BEGIN = "/* ROUTES-FROM-COLUMN:BEGIN — generated by scripts/generate_widget_routing_docs.py; do not edit by hand."
END = "ROUTES-FROM-COLUMN:END */"


def block_for(widget_id: str, rows: list[dict]) -> str:
    mine = [r for r in rows
            if r["archetype_v2"] == widget_id and r["v2_confidence"] == "high"]
    mine.sort(key=lambda r: (r["subject"], r["class_level"],
                             int(r["chapter_order"]), r["concept"]))
    lines = [BEGIN,
             "   The archetype column's HIGH verdicts naming this widget — the only",
             "   band the server routes on. Regenerate after any column change.",
             ""]
    if not mine:
        lines.append("   ZERO concepts route here at high confidence. That is a FINDING —")
        lines.append("   it is exactly how field_lines sat wired-and-unused — not a gap in")
        lines.append("   this file. Check the column before assuming the widget is used.")
    else:
        lines.append(f"   {len(mine)} concept(s):")
        for r in mine:
            lines.append(f"   - [{r['subject'][:4]}{r['class_level']} "
                         f"ch{r['chapter_order']}] {r['concept']}")
            ev = " ".join((r["v2_evidence"] or "").split())[:150]
            lines.append(f"     {ev}")
    lines.append(END)
    return "\n".join(lines) + "\n"


def stamp(path: str, block: str) -> tuple[str, bool]:
    src = open(path, encoding="utf-8").read()
    if BEGIN in src:
        head, rest = src.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        new = head + block.rstrip("\n") + tail
    else:
        new = block + src
    return new, new != src


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any file's block differs from the CSV")
    args = ap.parse_args()

    rows = list(csv.DictReader(open(CSV_PATH, encoding="utf-8")))
    drifted = []
    for wid, d in WIDGET_DIRS.items():
        path = os.path.join(ROOT, "lib", "widgets", d, "index.tsx")
        block = block_for(wid, rows)
        new, changed = stamp(path, block)
        if changed:
            drifted.append(wid)
            if not args.check:
                open(path, "w", encoding="utf-8").write(new)
    if args.check and drifted:
        print(f"ROUTING DOC DRIFT in: {', '.join(drifted)} — run "
              f"scripts/generate_widget_routing_docs.py")
        return 1
    print(("checked" if args.check else "stamped")
          + f" {len(WIDGET_DIRS)} widgets; "
          + (f"{len(drifted)} updated" if not args.check else "no drift"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
