/**
 * What you screenshot is what publishes.
 *
 * It was not. The frog heart's three-group split was proposed, rendered,
 * screenshotted and confirmed from THIS fixture on 2026-09-11 — and lived
 * only here. The API draft `apply_review.py` would have published had no
 * groups at all, so every piece of evidence anyone looked at came from a
 * document nobody was going to ship. It surfaced a day later, when the TS
 * gate refused that draft for having twelve labels in one group.
 *
 * The fixture is now generated by scripts/sync-preview-fixture.mjs, and this
 * runs it in --check mode: one implementation, and a hand edit fails here
 * rather than quietly disagreeing with what ships.
 */
import { execFileSync } from 'node:child_process';
import { resolve } from 'node:path';

const root = resolve(__dirname, '../../../..');

test('preview fixtures are identical to the drafts they are generated from', () => {
  execFileSync('node', [resolve(root, 'scripts/sync-preview-fixture.mjs'), '--check'],
               { stdio: 'pipe' });
});
